version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
  frontend:
    image: node:18
    working_dir: /workspace/frontend
    volumes:
      - .:/workspace
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
